CREATE TABLE `student` (
	`indexid` INT(11) NOT NULL AUTO_INCREMENT,
	`account` VARCHAR(50) NOT NULL DEFAULT '0',
	`password` VARCHAR(50) NOT NULL DEFAULT '0',
	`phone` VARCHAR(50) NOT NULL DEFAULT '0',
	`mail` VARCHAR(50) NOT NULL DEFAULT '0',
	`username` VARCHAR(50) NOT NULL DEFAULT '0',
	`classes` VARCHAR(50) NOT NULL DEFAULT '0',
	`projectname` VARCHAR(50) NOT NULL DEFAULT '0',
	`createtime` DATETIME NOT NULL,
	`updatetime` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`indexid`)
)
COMMENT='学生表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=109;